import {
    FormApplicationDefaultInputs,
    canonicalizeFormApplication,
    inferFormApplicationMaxLength,
    normalizeFormApplication,
    normalizeFormApplicationDataType
} from './FormApplicationDefinition.js';

const LF = '\n';
const SCHEMA_KEYS = new Set(['name', 'table', 'display_name', 'displayName', 'primary_key', 'primaryKey', 'columns']);
const SCHEMA_COLUMN_KEYS = new Set([
    'name', 'type', 'nullable', 'primary_key', 'primaryKey', 'identity', 'auto_increment', 'autoIncrement',
    'default', 'max_length', 'maxLength', 'display_name', 'displayName', 'label'
]);

function textFile(lines) {
    return `${Array.isArray(lines) ? lines.join(LF) : String(lines).replace(/\r\n?/g, LF).replace(/\n+$/, '')}${LF}`;
}

function assertPlainObject(value, path) {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
        throw new TypeError(`${path} must be an object.`);
    }
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) throw new TypeError(`${path} must be a plain object.`);
    return value;
}

function assertAllowedKeys(value, allowed, path) {
    for (const key of Object.keys(value)) {
        if (!allowed.has(key)) throw new TypeError(`${path} contains unsupported property '${key}'.`);
    }
}

function pascalCase(value) {
    const result = String(value).split(/[^A-Za-z0-9]+/).filter(Boolean)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');
    return /^[0-9]/.test(result) ? `N${result}` : result;
}

function camelCase(value) {
    const pascal = pascalCase(value);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function kebabCase(value) {
    return String(value).replace(/_/g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function sqlIdentifier(provider, value) {
    if (provider === 'sqlserver') return `[${value}]`;
    if (provider === 'mysql') return `\`${value}\``;
    return `"${value}"`;
}

function sqlType(provider, field) {
    const length = field.max_length || field.validation.max_length || 255;
    const maps = {
        sqlite: {
            integer: 'INTEGER', long: 'INTEGER', decimal: 'REAL', number: 'REAL', boolean: 'INTEGER',
            text: 'TEXT', date: 'TEXT', datetime: 'TEXT', guid: 'TEXT', binary: 'BLOB', json: 'TEXT'
        },
        sqlserver: {
            integer: 'INT', long: 'BIGINT', decimal: 'DECIMAL(18, 2)', number: 'FLOAT', boolean: 'BIT',
            text: `NVARCHAR(${Math.min(length, 4000)})`, date: 'DATE', datetime: 'DATETIME2',
            guid: 'UNIQUEIDENTIFIER', binary: 'VARBINARY(MAX)', json: 'NVARCHAR(MAX)'
        },
        postgresql: {
            integer: 'INTEGER', long: 'BIGINT', decimal: 'NUMERIC(18, 2)', number: 'DOUBLE PRECISION', boolean: 'BOOLEAN',
            text: length ? `VARCHAR(${length})` : 'TEXT', date: 'DATE', datetime: 'TIMESTAMPTZ',
            guid: 'UUID', binary: 'BYTEA', json: 'JSONB'
        },
        mysql: {
            integer: 'INT', long: 'BIGINT', decimal: 'DECIMAL(18, 2)', number: 'DOUBLE', boolean: 'TINYINT(1)',
            text: length <= 65535 ? `VARCHAR(${length})` : 'LONGTEXT', date: 'DATE', datetime: 'DATETIME(6)',
            guid: 'CHAR(36)', binary: 'LONGBLOB', json: 'JSON'
        }
    };
    return maps[provider][field.db_type];
}

function sqlLiteral(value, provider) {
    if (value === null || value === undefined) return null;
    if (typeof value === 'boolean') return provider === 'postgresql' ? (value ? 'TRUE' : 'FALSE') : (value ? '1' : '0');
    if (typeof value === 'number') return String(value);
    return `'${String(value).replaceAll("'", "''")}'`;
}

function createSql(definition) {
    const provider = definition.persistence.provider;
    const table = sqlIdentifier(provider, definition.table.name);
    const columns = definition.fields.map(field => {
        const name = sqlIdentifier(provider, field.column_name);
        if (field.identity) {
            const identity = {
                sqlite: `${name} INTEGER PRIMARY KEY AUTOINCREMENT`,
                sqlserver: `${name} ${sqlType(provider, field)} IDENTITY(1,1) PRIMARY KEY`,
                postgresql: `${name} ${sqlType(provider, field)} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`,
                mysql: `${name} ${sqlType(provider, field)} AUTO_INCREMENT PRIMARY KEY`
            }[provider];
            return `  ${identity}`;
        }
        const parts = [`  ${name} ${sqlType(provider, field)}`];
        if (!field.nullable) parts.push('NOT NULL');
        if (field.primary_key) parts.push('PRIMARY KEY');
        const defaultValue = sqlLiteral(field.default, provider);
        if (defaultValue !== null) parts.push(`DEFAULT ${defaultValue}`);
        return parts.join(' ');
    });
    const prefix = provider === 'sqlserver'
        ? `IF OBJECT_ID(N'${definition.table.name}', N'U') IS NULL${LF}BEGIN${LF}CREATE TABLE ${table} (`
        : `CREATE TABLE IF NOT EXISTS ${table} (`;
    const suffix = provider === 'sqlserver' ? `);${LF}END;` : ');';
    return textFile([
        '-- Generated preview. Review the schema diff before applying.',
        '-- No database connection or write was performed by Bricks4Agent.',
        prefix,
        columns.join(`,${LF}`),
        suffix
    ]);
}

function rollbackSql(definition) {
    const provider = definition.persistence.provider;
    const table = sqlIdentifier(provider, definition.table.name);
    const statement = provider === 'sqlserver'
        ? `IF OBJECT_ID(N'${definition.table.name}', N'U') IS NOT NULL DROP TABLE ${table};`
        : `DROP TABLE IF EXISTS ${table};`;
    return textFile([
        '-- DESTRUCTIVE PREVIEW: execute only after explicit review and backup.',
        '-- This rollback is limited to the generated table named below.',
        statement
    ]);
}

function csharpType(field, nullable = field.nullable) {
    const base = {
        integer: 'int', long: 'long', decimal: 'decimal', number: 'double', boolean: 'bool', text: 'string',
        date: 'DateOnly', datetime: 'DateTimeOffset', guid: 'Guid', binary: 'byte[]', json: 'string'
    }[field.db_type];
    if (!nullable) return base;
    return base === 'string' || base === 'byte[]' ? `${base}?` : `${base}?`;
}

function csharpDefault(field) {
    if (field.nullable) return '';
    if (field.db_type === 'text' || field.db_type === 'json') return ' = string.Empty;';
    if (field.db_type === 'binary') return ' = Array.Empty<byte>();';
    return '';
}

function modelSource(definition) {
    const className = pascalCase(definition.table.name);
    const lines = [
        'using BaseOrm;',
        '',
        'namespace GeneratedFormApplication.Models;',
        '',
        `[Table("${definition.table.name}")]`,
        `public sealed class ${className}`,
        '{'
    ];
    for (const field of definition.fields) {
        if (field.primary_key) lines.push(`  [Key(AutoIncrement = ${field.identity ? 'true' : 'false'})]`);
        lines.push(`  [Column("${field.column_name}")]`);
        if (!field.nullable) lines.push('  [Required]');
        const maxLength = field.max_length || field.validation.max_length;
        if (maxLength) lines.push(`  [MaxLength(${maxLength})]`);
        lines.push(`  public ${csharpType(field)} ${pascalCase(field.column_name)} { get; set; }${csharpDefault(field)}`);
        lines.push('');
    }
    if (lines.at(-1) === '') lines.pop();
    lines.push('}', '');
    const writable = definition.fields.filter(field => !field.identity);
    lines.push(`public sealed record Create${className}Request(`);
    lines.push(writable.map((field, index) => `  ${csharpType(field)} ${pascalCase(field.column_name)}${index + 1 < writable.length ? ',' : ''}`).join(LF));
    lines.push(');', '');
    lines.push(`public sealed record Update${className}Request(`);
    lines.push(writable.map((field, index) => `  ${csharpType(field, true)} ${pascalCase(field.column_name)}${index + 1 < writable.length ? ',' : ''}`).join(LF));
    lines.push(');');
    return textFile(lines);
}

function serviceSource(definition) {
    const className = pascalCase(definition.table.name);
    const primary = definition.fields.find(field => field.primary_key);
    const primaryType = csharpType(primary, false);
    const createFields = definition.fields.filter(field => !field.identity);
    const updateFields = definition.fields.filter(field => !field.primary_key && !field.identity);
    return textFile([
        'using BaseOrm;',
        'using GeneratedFormApplication.Models;',
        '',
        'namespace GeneratedFormApplication.Services;',
        '',
        `public sealed class ${className}Service`,
        '{',
        '  private readonly BaseDb _db;',
        `  public ${className}Service(BaseDb db) => _db = db;`,
        '',
        `  public IReadOnlyList<${className}> List() => _db.GetAll<${className}>();`,
        `  public ${className}? Get(${primaryType} id) => _db.Get<${className}>(id);`,
        '',
        `  public ${className} Create(Create${className}Request request)`,
        '  {',
        `    var entity = new ${className}`, '{',
        createFields.map(field => `      ${pascalCase(field.column_name)} = request.${pascalCase(field.column_name)}`).join(`,${LF}`),
        '    };',
        '    var id = _db.Insert(entity);',
        ...(primary.identity ? [`    entity.${pascalCase(primary.column_name)} = (${primaryType})id;`] : []),
        '    return entity;',
        '  }',
        '',
        `  public ${className}? Update(${primaryType} id, Update${className}Request request)`,
        '  {',
        `    var entity = _db.Get<${className}>(id);`,
        '    if (entity is null) return null;',
        ...updateFields.map(field => {
            const property = pascalCase(field.column_name);
            const assignment = ['string', 'byte[]'].includes(csharpType(field, false))
                ? `request.${property}`
                : `request.${property}.Value`;
            return `    if (request.${property} is not null) entity.${property} = ${assignment};`;
        }),
        '    _db.Update(entity);',
        '    return entity;',
        '  }',
        '',
        `  public bool Delete(${primaryType} id) => _db.Delete<${className}>(id) > 0;`,
        '}'
    ]);
}

function endpointSource(definition) {
    const className = pascalCase(definition.table.name);
    const variable = camelCase(className);
    const primary = definition.fields.find(field => field.primary_key);
    const primaryType = csharpType(primary, false);
    const auth = definition.api.auth_required ? '.RequireAuthorization()' : '';
    const operations = new Set(definition.api.operations);
    const lines = [
        'using GeneratedFormApplication.Models;',
        'using GeneratedFormApplication.Services;',
        '',
        'namespace GeneratedFormApplication.Api;',
        '',
        `public static class ${className}Endpoints`,
        '{',
        '  public static IEndpointRouteBuilder MapGeneratedFormApplication(this IEndpointRouteBuilder app)',
        '  {',
        `    var group = app.MapGroup("${definition.api.route}")${auth};`
    ];
    if (operations.has('list')) lines.push(`    group.MapGet("/", (${className}Service service) => Results.Ok(service.List()));`);
    if (operations.has('get')) lines.push(`    group.MapGet("/{id}", (${primaryType} id, ${className}Service service) => service.Get(id) is { } ${variable} ? Results.Ok(${variable}) : Results.NotFound());`);
    if (operations.has('create')) lines.push(`    group.MapPost("/", (Create${className}Request request, ${className}Service service) => Results.Created("${definition.api.route}", service.Create(request)));`);
    if (operations.has('update')) lines.push(`    group.MapPut("/{id}", (${primaryType} id, Update${className}Request request, ${className}Service service) => service.Update(id, request) is { } ${variable} ? Results.Ok(${variable}) : Results.NotFound());`);
    if (operations.has('delete')) lines.push(`    group.MapDelete("/{id}", (${primaryType} id, ${className}Service service) => service.Delete(id) ? Results.NoContent() : Results.NotFound());`);
    lines.push('    return app;', '  }', '}');
    return textFile(lines);
}

function bootstrapSource(definition) {
    const className = pascalCase(definition.table.name);
    const provider = definition.persistence.provider;
    const factoryCall = {
        sqlite: 'BaseDb.UseSqlite(connectionString)',
        sqlserver: 'BaseDb.UseSqlServer(connectionString)',
        postgresql: 'BaseDb.UsePostgreSql(connectionString)',
        mysql: 'BaseDb.UseMySql(connectionString)'
    }[provider];
    const registrationLines = provider === 'sqlite'
        ? [
            `    var connectionString = configuration.GetConnectionString("${definition.persistence.connection_string_name}");`,
            '    if (string.IsNullOrWhiteSpace(connectionString))',
            '    {',
            '      var dataDirectory = Path.Combine(environment.ContentRootPath, "data");',
            '      Directory.CreateDirectory(dataDirectory);',
            `      var databasePath = Path.Combine(dataDirectory, "${definition.application_id}.db");`,
            '      connectionString = $"Data Source={databasePath}";',
            '    }',
            `    services.AddSingleton<BaseDb>(_ => ${factoryCall});`
        ]
        : [
            `    var connectionString = configuration.GetConnectionString("${definition.persistence.connection_string_name}");`,
            '    if (string.IsNullOrWhiteSpace(connectionString))',
            '    {',
            `      throw new InvalidOperationException("ConnectionStrings:${definition.persistence.connection_string_name} is required for ${provider}.");`,
            '    }',
            `    services.AddSingleton<BaseDb>(_ => ${factoryCall});`
        ];
    return textFile([
        'using BaseOrm;',
        `using GeneratedFormApplication.Services;`,
        'using Microsoft.Extensions.Configuration;',
        'using Microsoft.Extensions.DependencyInjection;',
        'using Microsoft.Extensions.Hosting;',
        '',
        'namespace GeneratedFormApplication.Generated;',
        '',
        'public static class FormApplicationBootstrap',
        '{',
        '  public static IServiceCollection AddGeneratedFormApplication(',
        '    this IServiceCollection services,',
        '    IConfiguration configuration,',
        '    IHostEnvironment environment)',
        '  {',
        '    ArgumentNullException.ThrowIfNull(services);',
        '    ArgumentNullException.ThrowIfNull(configuration);',
        '    ArgumentNullException.ThrowIfNull(environment);',
        ...registrationLines,
        `    services.AddScoped<${className}Service>();`,
        '    return services;',
        '  }',
        '}'
    ]);
}

function integrationReadme(definition) {
    return textFile([
        '# Generated form application integration',
        '',
        'The generated bundle is preview-only and never applies its SQL automatically.',
        '',
        'Add these namespaces and calls to `Program.cs`:',
        '',
        '```csharp',
        'using GeneratedFormApplication.Api;',
        'using GeneratedFormApplication.Generated;',
        '',
        'var builder = WebApplication.CreateBuilder(args);',
        'builder.Services.AddGeneratedFormApplication(builder.Configuration, builder.Environment);',
        '',
        'var app = builder.Build();',
        'app.MapGeneratedFormApplication();',
        '```',
        '',
        `The connection-string key is \`${definition.persistence.connection_string_name}\`.`,
        definition.persistence.provider === 'sqlite'
            ? `When it is missing or blank, the runtime creates \`data/${definition.application_id}.db\` below the host content root.`
            : `For provider \`${definition.persistence.provider}\`, supply the connection string through user-secrets or \`ConnectionStrings__${definition.persistence.connection_string_name}\`.`,
        '',
        'Review the forward SQL and rollback SQL before executing either one. The generated bootstrap does not run migrations.'
    ]);
}

function pageDefinition(definition) {
    const fields = definition.fields.map(field => ({
        fieldName: field.column_name,
        fieldType: field.input.field_type,
        component: field.input.component,
        label: field.display_name,
        required: field.validation.required,
        defaultValue: field.default,
        validation: { ...field.validation },
        formRow: field.layout.row,
        formCol: field.layout.column_span,
        options: { ...field.input.options }
    }));
    const api = {};
    const operations = new Set(definition.api.operations);
    if (operations.has('list')) api.list = definition.api.route;
    if (operations.has('get')) api.get = `${definition.api.route}/:id`;
    if (operations.has('create')) api.create = definition.api.route;
    if (operations.has('update')) api.update = `${definition.api.route}/:id`;
    if (operations.has('delete')) api.delete = `${definition.api.route}/:id`;
    return {
        name: definition.form.page_name,
        type: 'form',
        description: definition.display_name,
        components: [...new Set(fields.map(field => field.component))].sort().map(name => ({ name })),
        services: [],
        fields,
        api,
        behaviors: { onSave: operations.has('update') ? 'createOrUpdate' : 'create' },
        styles: { layout: 'grid', columns: 12 }
    };
}

function developmentConfig(definition, connectionString, includeConnectionString) {
    const value = includeConnectionString && connectionString
        ? connectionString
        : definition.persistence.provider === 'sqlite'
            ? `Data Source=${definition.persistence.sqlite_file}`
            : '';
    return textFile(JSON.stringify({
        ConnectionStrings: { [definition.persistence.connection_string_name]: value },
        FormApplication: {
            Provider: definition.persistence.provider,
            ApplyDatabase: false,
            Note: value ? 'Generated preview configuration.' : 'Set the connection string via user-secrets or environment variables.'
        }
    }, null, 2));
}

function schemaColumnToField(column, index, schemaPrimaryKey) {
    assertPlainObject(column, `schema.columns[${index}]`);
    assertAllowedKeys(column, SCHEMA_COLUMN_KEYS, `schema.columns[${index}]`);
    const name = column.name;
    const dbType = normalizeFormApplicationDataType(column.type, `schema.columns[${index}].type`);
    const primaryKey = column.primary_key === true || column.primaryKey === true || column.name === schemaPrimaryKey;
    const schemaType = String(column.type).trim().toLowerCase().replace(/\s*\(.*\)$/, '');
    const defaults = primaryKey
        ? ['hidden', 'TextInput']
        : schemaType === 'email'
            ? ['email', 'TextInput']
            : FormApplicationDefaultInputs[dbType];
    const maxLength = column.max_length ?? column.maxLength ?? inferFormApplicationMaxLength(column.type);
    const field = {
        field_id: `field_${String(name).toLowerCase()}`,
        column_name: name,
        display_name: column.label ?? column.display_name ?? column.displayName ?? name,
        db_type: dbType,
        nullable: column.nullable === true,
        primary_key: primaryKey,
        identity: column.identity === true || column.auto_increment === true || column.autoIncrement === true,
        default: column.default ?? null,
        icon: primaryKey ? 'number' : defaults[0],
        input: { field_type: defaults[0], component: defaults[1], options: {} },
        validation: { required: !primaryKey && column.nullable !== true },
        layout: {
            row: index + 1,
            column: 1,
            column_span: primaryKey ? 12 : 6,
            row_span: 1,
            width: null,
            height: null
        },
        order: index + 1
    };
    if (maxLength) {
        field.max_length = maxLength;
        field.validation.max_length = maxLength;
    }
    return field;
}

export function schemaToFormApplication(schema, options = {}) {
    assertPlainObject(schema, 'schema');
    assertAllowedKeys(schema, SCHEMA_KEYS, 'schema');
    if (!Array.isArray(schema.columns) || schema.columns.length === 0) throw new TypeError('schema.columns must be a non-empty array.');
    const applicationId = options.applicationId;
    const provider = options.provider ?? 'sqlite';
    const tableName = schema.name ?? schema.table;
    const explicitlyMarkedPrimaryKeys = schema.columns
        .filter(column => column?.primary_key === true || column?.primaryKey === true)
        .map(column => column.name);
    const schemaPrimaryKey = schema.primary_key ?? schema.primaryKey ?? explicitlyMarkedPrimaryKeys[0];
    if (!schemaPrimaryKey) {
        throw new TypeError('schema must identify exactly one primary key through schema.primary_key or a marked column.');
    }
    if (!schema.columns.some(column => column?.name === schemaPrimaryKey)) {
        throw new TypeError(`schema.primary_key does not reference a column: ${schemaPrimaryKey}`);
    }
    const definition = {
        schema_version: 1,
        application_id: applicationId,
        display_name: options.displayName ?? schema.display_name ?? schema.displayName ?? applicationId,
        source: { mode: 'import', dialect: provider },
        persistence: {
            provider,
            connection_string: options.connectionString ?? (provider === 'sqlite' ? `Data Source=data/${applicationId}.db` : null),
            connection_string_name: options.connectionStringName ?? 'DefaultConnection',
            sqlite_file: provider === 'sqlite' ? `data/${applicationId}.db` : null
        },
        table: {
            name: tableName,
            mode: 'create',
            primary_key: schemaPrimaryKey
        },
        fields: schema.columns.map((column, index) => schemaColumnToField(column, index, schemaPrimaryKey)),
        form: { page_name: `${pascalCase(applicationId)}FormPage`, submit_label: 'Save' },
        api: { route: `/api/${kebabCase(applicationId)}`, operations: [...['list', 'get', 'create', 'update', 'delete']], auth_required: true },
        generation: { target: 'spa-net10', output_name: kebabCase(applicationId), mode: 'preview', apply_database: false }
    };
    return normalizeFormApplication(definition, { connectionString: definition.persistence.connection_string });
}

export function generateFormApplicationBundle(definition, options = {}) {
    const connectionString = options.connectionString !== undefined
        ? options.connectionString
        : definition?.persistence?.connection_string;
    const normalized = normalizeFormApplication(definition, { connectionString });
    const page = pageDefinition(normalized);
    const forward = createSql(normalized);
    const rollback = rollbackSql(normalized);
    const model = modelSource(normalized);
    const service = serviceSource(normalized);
    const endpoints = endpointSource(normalized);
    const bootstrap = bootstrapSource(normalized);
    const development = developmentConfig(normalized, typeof connectionString === 'string' ? connectionString.trim() : '', options.includeConnectionString === true);
    const readme = integrationReadme(normalized);
    const normalizedJson = canonicalizeFormApplication(normalized, { connectionString });
    const pageJson = textFile(JSON.stringify(page, null, 2));
    const files = {
        'definition/form-application.json': normalizedJson,
        'frontend/pages/form.page.json': pageJson,
        [`database/${normalized.persistence.provider}/001_create_${normalized.table.name}.sql`]: forward,
        [`database/${normalized.persistence.provider}/001_rollback_${normalized.table.name}.sql`]: rollback,
        [`backend/Models/${pascalCase(normalized.table.name)}.cs`]: model,
        [`backend/Services/${pascalCase(normalized.table.name)}Service.cs`]: service,
        [`backend/Api/${pascalCase(normalized.table.name)}Endpoints.cs`]: endpoints,
        'backend/Generated/FormApplicationBootstrap.cs': bootstrap,
        'backend/appsettings.Development.json': development,
        'INTEGRATION.md': readme
    };
    return {
        definition: JSON.parse(normalizedJson),
        pageDefinition: page,
        sql: { provider: normalized.persistence.provider, forward, rollback },
        csharp: { model, service, endpoints, bootstrap },
        api: { route: normalized.api.route, operations: [...normalized.api.operations], source: endpoints },
        files
    };
}
